language: python
python:
  - pypy3.5-6.0
  - pypy3.5
  - pypy2.7-6.0
  - pypy
  - 3.8
  - 3.7
  - 3.6
  - 2.7
  - nightly

env:
  global:
    - CC_TEST_REPORTER_ID=aa9820d7f18c6a86da387e2604f592f37845d0dac88afb10f73738872647c321
    - MONGODB=4.0.11
  matrix:
    - MONTY_ENABLE_BSON=true
    - MONTY_ENABLE_BSON=

matrix:
  fast_finish: true
  allow_failures:
    - python: pypy3.5-6.0
    - python: pypy3.5
    - python: pypy2.7-6.0
    - python: pypy
    - python: nightly

before_install:
  - wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - pip install pip -U
  - pip install pytest-cov
  - pip install pytest-env-info
  - pip install coveralls

install:
  - pip install pymongo
  - pip install lmdb
  - python setup.py install

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
  - "${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongo --eval 'db.adminCommand( { setFeatureCompatibilityVersion: \"4.0\" } )'"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pytest --cov montydb --storage memory
  - pytest --cov montydb --storage flatfile --cov-append
  - pytest --cov montydb --storage lightning --cov-append
  - pytest --cov montydb --storage sqlite --cov-append

after_script:
  - pkill mongod

after_success:
  - coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

sudo: false

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: davidlatwe
  password: $PYPI_PASSWORD
  on:
    tags: true
    repo: davidlatwe/montydb
    branch: master
    python: 3.6
