# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up MongoDB 3.6
      uses: supercharge/mongodb-github-action@1.4.0
      with:
        mongodb-version: 3.6
        mongodb-port: 30036

    - name: Set up MongoDB 4.0
        uses: supercharge/mongodb-github-action@1.4.0
        with:
          mongodb-version: 4.0
          mongodb-port: 30040

    - name: Set up MongoDB 4.2
        uses: supercharge/mongodb-github-action@1.4.0
        with:
          mongodb-version: 4.2
          mongodb-port: 30042

#    - name: Set up MongoDB 4.4
#        uses: supercharge/mongodb-github-action@1.4.0
#        with:
#          mongodb-version: 4.4
#          mongodb-port: 30044

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install pymongo lmdb

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: >
        pytest
        --mongodb localhost:30036
        --mongodb localhost:30040
        --mongodb localhost:30042
